### ISSUE TITLE
Void Eruption causes huge FPS issues

### ISSUE THREAD

**Issue by aname23** [tullamods/Dominos#733]
**Addon Version**
10.0.18-Retail

**World of Warcraft Version**
Retail

**Notes:**
Tested with just Dominos, Dominos Config, BugSack/Bug Grabber on.

**Description of bug:**
When I enter void eruption on shadow priest, my entire game locks up to the point that it is unplayable.

After a UI /reload, it seems to take a couple of minutes (or combats?) before the issue comes back.

With dominos off, it functionals normally.

The only error which appears in BugSack is this. The error seems to appear before I press void eruption though, so I don't know if it's related:

```
186x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'DominosActionButton51:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:355: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:415: in function `Update'
[string "@FrameXML/ActionButton.lua"]:367: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:803: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:216: in function <FrameXML/ActionButton.lua:213>

Locals:
Skipped (In Encounter)
```

**Video showing the problem**
https://gfycat.com/quarterlymedicalfoal

If there's any other info I can provide please let me know.

Thanks

**Comment by indeed-a-genius** [comment]
I'm getting regular stuttering during combat since patch 10.0.5
On a BM hunter.

**Comment by Tuller** [comment]
The good news is you've found what looks to be a highly reproducible version of the bug I've been trying to track down for some time. The FPS drops themselves are likely caused by the error happening over and over in quick succession. Can you enable taint logging and attach the results?  Steps:
1. Enable [detailed taint logging](https://wowpedia.fandom.com/wiki/CVar_taintLog) via `/console taintLog 2`
2. Get into position, and `/reload`. This will start a fresh log.
3. Wait for the FPS issues to start occurring
4. Once they do. `/reload` again. This will save information from the log to disk.
5. Grab the file `taint.log` from the logs folder within your World of Warcraft install directory (`World of Warcraft\_retail_\Logs`) and attach it here.
7. Disable taint logging via `/console taintLog 0` followed by a `/reload`

**Comment by indeed-a-genius** [comment]
taint.log attached
[taint.log](https://github.com/tullamods/Dominos/files/10527806/taint.log)

**Comment by aname23** [comment]
Hey Tuller

Turned taint logging on and went to reproduce the same thing as my initial video, and I can't get it to happen again!

I'll keep trying and attach a taint log when I can.

**Comment by aname23** [comment]
OK got it to happened again, just needed to drop in/out of combat a couple of times, and cast a bunch of different spells.... it's like the lag builds up over time, starts barely noticeable and then becomes really bad after a while.

Taint log attached.

[taint.log](https://github.com/tullamods/Dominos/files/10527963/taint.log)

**Comment by Tuller** [comment]
Thanks both, This looks like a similar issue to #701. Are you able to use hotkeys when this happens?

I'm roughly at the point where I may give up and just write my own action button implementation again :)

**Comment by indeed-a-genius** [comment]
I'm able to use hotkeys, yes.
#701 affected me too, but a simple reload helped. 
However since 10.0.5 the game is close to unplayable with Dominos enabled, because of the freezes.

**Comment by aname23** [comment]
Yes I'm able to use hotkeys during the lag.

I do sometimes get a dominos bug after hearthing / changing zones where my hotkeys break until I reload UI - but unrelated.

**Comment by Tuller** [comment]
Blizzard has pushed an update that should resolve this specific issue.

**Comment by indeed-a-genius** [comment]
Doesn't seem resolved for me.
[taint.log](https://github.com/tullamods/Dominos/files/10590443/taint-new.log)

**Comment by aname23** [comment]
Hi Tuller,

I'm still getting the same too - not as laggy as before but still pretty bad.

Attaching a newer taint log.
[taint.log](https://github.com/tullamods/Dominos/files/10668898/taint.log)


Thanks
