### ISSUE TITLE
Log other char Action Bar issue -Classic WLK

### ISSUE THREAD

**Issue by Bsumi** [tullamods/Dominos#780]
Dear author, hello, I have a mage, hunter, paladin, shaman, priest, and druid. Every time I log in to the mage and shaman, the action bar configuration will not load. After I select it manually, there will be an error message and I need to reloadui. Please help me, thanks! The error code is as follows

Dominos: Failed to unload ProgressBars
Interface/AddOns/Dominos_Progress/main.lua:68: bad argument #1 to 'pairs' (table expected, got nil)

**World of Warcraft Version**
Classic WLK

**Comment by Bsumi** [comment]
update the 10.1.5 addon,still have a issues @ @  Log the mage ang shaman the action bar buged

**Comment by Bsumi** [comment]
15x Dominos_Progress/config.lua:93: attempt to index field 'db' (a nil value)
[string "@Dominos_Progress/config.lua"]:93: in function <Dominos_Progress/config.lua:92>
[string "=(tail call)"]: ?
[string "@TomTom/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:215: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:164>
[string "@TomTom/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1193: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1110>
[string "@TomTom/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1639: in function `FeedGroup'
[string "@TomTom/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1564: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1548>
[string "=[C]"]: ?
[string "@TomTom/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <TomTom/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@TomTom/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@TomTom/libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@TomTom/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1675: in function `FeedGroup'
[string "@TomTom/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1919: in function `Open'
[string "@Dominos/Dominos.lua"]:375: in function `ShowOptionsFrame'
[string "@Dominos/Dominos.lua"]:842: in function `OnClick'
[string "@AtlasLootClassic/Libs/LibDBIcon-1.0-52/LibDBIcon-1.0.lua"]:170: in function `oclick'
[string "@MBB/MBB.lua"]:427: in function <MBB/MBB.lua:415>

Locals:
self = <table> {
 SetBarMode = <function> defined @Dominos_Progress/config.lua:66
 Upgrade = <function> defined @Dominos_Progress/config.lua:20
 GetColor = <function> defined @Dominos_Progress/config.lua:120
 Init = <function> defined @Dominos_Progress/config.lua:7
 SetGoldGoal = <function> defined @Dominos_Progress/config.lua:108
 GoldGoal = <function> defined @Dominos_Progress/config.lua:104
 SkipInactiveModes = <function> defined @Dominos_Progress/config.lua:100
 SetOneBarMode = <function> defined @Dominos_Progress/config.lua:88
 SetSkipInactiveModes = <function> defined @Dominos_Progress/config.lua:96
 OneBarMode = <function> defined @Dominos_Progress/config.lua:92
 GetDefaults = <function> defined @Dominos_Progress/config.lua:40
 GetBarMode = <function> defined @Dominos_Progress/config.lua:78
 SetColor = <function> defined @Dominos_Progress/config.lua:112
}
(*temporary) = nil
(*temporary) = "attempt to index field 'db' (a nil value)"

**Comment by Bsumi** [comment]
@Tuller

**Comment by Bsumi** [comment]
28x Dominos/Dominos.lua:173: script ran too long
[string "@Dominos/Dominos.lua"]:173: in function `Load'
[string "@Dominos/Dominos.lua"]:68: in function <Dominos/Dominos.lua:66>
[string "=[C]"]: ?
[string "@AckisRecipeList/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:70: in function <...s/AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@AckisRecipeList/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@AckisRecipeList/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:630: in function <...s/AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:615>

Locals:
self = <table> {
 CreateDatabase = <function> defined @Dominos/Dominos.lua:220
 GetRightClickUnit = <function> defined @Dominos/Dominos.lua:586
 NumBars = <function> defined @Dominos/Dominos.lua:678
 BindableButton = <table> {
 }
 SetClickThroughForFrames = <function> defined @Dominos/Dominos.lua:561
 modules = <table> {
 }
 SetLinkedOpacity = <function> defined @Dominos/Dominos.lua:726
 CopyProfile = <function> defined @Dominos/Dominos.lua:326
 DeleteProfile = <function> defined @Dominos/Dominos.lua:317
 ListProfiles = <function> defined @Dominos/Dominos.lua:336
 SetOpacityForFrames = <function> defined @Dominos/Dominos.lua:482
 SetDefaultModulePrototype = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:409
 OnProfileReset = <function> defined @Dominos/Dominos.lua:130
 FadeManager = <table> {
 }
 Unload = <function> defined @Dominos/Dominos.lua:185
 IsEnabled = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:451
 SetRightClickUnit = <function> defined @Dominos/Dominos.lua:581
 LIBKEYBOUND_ENABLED = <function> defined @Dominos/Dominos.lua:103
 OnUpgradeDatabase = <function> defined @Dominos/Dominos.lua:77
 UnregisterMessage = <function> defined @TomTom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 GetOverrideBar = <function> defined @Dominos/Dominos.lua:660
 PrintVersion = <function> defined @Dominos/Dominos.lua:788
 ShowBindingText = <function> defined @Dominos/Dominos.lua:596
 ResetProfile = <function> defined @Dominos/Dominos.lua:332
 db = <table> {
 }
 SetUseOverrideUI = <function> defined @Dominos/Dominos.lua:621
 NewMenu = <function> defined @Dominos/Dominos.lua:384
 ACTION_BUTTON_HOTKEY_BUTTON = "HOTKEY"
 Reload = <function> defined @Dominos/Dominos.lua:210
 ShowOptionsFrame = <function> defined @Dominos/Dominos.lua:371
 OnEnable = <function> defined @Dominos/Dominos.lua:66
 SetOverrideBar = <function> defined @Dominos/Dominos.lua:650
 OnProfileShutdown = <function> defined @Dominos/Dominos.lua:135
 IsConfigAddonEnabled = <function> defined @Dominos/Dominos.lua:396
 MatchProfile = <function> defined @Dominos/Dominos.lua:349
 SetAlignmentGridEnabled = <function> defined @Dominos/Dominos.lua:758
 OnInitialize = <function> defined @Dominos/Dominos.lua:35
 UnregisterAllEvents = <function> defined @TomTom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 ToggleLockedFrames = <function> defined @Dominos/Dominos.lua:447
 ShowMacroText = <function> defined @Dominos/Dominos.lua:606
 GetDatabaseDefaults = <function> defined @Dominos/Dominos.lua:242
 SaveProfile = <function> defined @Dominos/Dominos.lua:300
 ToggleFrames = <function> defined @Dominos/Dominos.lua:554
 OnProfileChanged = <function> defined @Dominos/Dominos.lua:120
 GetName = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:279
 RegisterCallback = <function> defined @TomTom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 name = "Dominos"
 HideFrames = <function> defined @Dominos/Dominos.lua:548
 Disable = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:314
 LIBKEYBOUND_DISABLED = <function> defined @Dominos/Dominos.lua:107
 BlizzardActionButtons = <table> {
 }
 Print = <function> defined @AckisRecipeList/libs/AceConsole-3.0/AceConsole-3.0.lua:50
 OnLaunch = <function> defined @Dominos/Do

**Comment by Tuller** [comment]
The progress bar related issues should be fixed.

**Comment by Bsumi** [comment]
sry still have issues 

59x Dominos/Dominos.lua:173: script ran too long
[string "@Dominos/Dominos.lua"]:173: in function `Load'
[string "@Dominos/Dominos.lua"]:68: in function <Dominos/Dominos.lua:66>
[string "=[C]"]: ?
[string "@AddOnSkins/Libs/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...s/AddOnSkins/Libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@AddOnSkins/Libs/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@AddOnSkins/Libs/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...s/AddOnSkins/Libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 CreateDatabase = <function> defined @Dominos/Dominos.lua:220
 GetRightClickUnit = <function> defined @Dominos/Dominos.lua:586
 NumBars = <function> defined @Dominos/Dominos.lua:678
 BindableButton = <table> {
 }
 SetClickThroughForFrames = <function> defined @Dominos/Dominos.lua:561
 modules = <table> {
 }
 SetLinkedOpacity = <function> defined @Dominos/Dominos.lua:726
 CopyProfile = <function> defined @Dominos/Dominos.lua:326
 DeleteProfile = <function> defined @Dominos/Dominos.lua:317
 ListProfiles = <function> defined @Dominos/Dominos.lua:336
 SetOpacityForFrames = <function> defined @Dominos/Dominos.lua:482
 SetDefaultModulePrototype = <function> defined @AddOnSkins/Libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 OnProfileReset = <function> defined @Dominos/Dominos.lua:130
 FadeManager = <table> {
 }
 Unload = <function> defined @Dominos/Dominos.lua:185
 IsEnabled = <function> defined @AddOnSkins/Libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 SetRightClickUnit = <function> defined @Dominos/Dominos.lua:581
 LIBKEYBOUND_ENABLED = <function> defined @Dominos/Dominos.lua:103
 OnUpgradeDatabase = <function> defined @Dominos/Dominos.lua:77
 UnregisterMessage = <function> defined @AddOnSkins/Libs/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 GetOverrideBar = <function> defined @Dominos/Dominos.lua:660
 PrintVersion = <function> defined @Dominos/Dominos.lua:788
 ShowBindingText = <function> defined @Dominos/Dominos.lua:596
 ResetProfile = <function> defined @Dominos/Dominos.lua:332
 db = <table> {
 }
 SetUseOverrideUI = <function> defined @Dominos/Dominos.lua:621
 NewMenu = <function> defined @Dominos/Dominos.lua:384
 ACTION_BUTTON_HOTKEY_BUTTON = "HOTKEY"
 Reload = <function> defined @Dominos/Dominos.lua:210
 ShowOptionsFrame = <function> defined @Dominos/Dominos.lua:371
 OnEnable = <function> defined @Dominos/Dominos.lua:66
 SetOverrideBar = <function> defined @Dominos/Dominos.lua:650
 OnProfileShutdown = <function> defined @Dominos/Dominos.lua:135
 IsConfigAddonEnabled = <function> defined @Dominos/Dominos.lua:396
 MatchProfile = <function> defined @Dominos/Dominos.lua:349
 SetAlignmentGridEnabled = <function> defined @Dominos/Dominos.lua:758
 OnInitialize = <function> defined @Dominos/Dominos.lua:35
 UnregisterAllEvents = <function> defined @AddOnSkins/Libs/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 ToggleLockedFrames = <function> defined @Dominos/Dominos.lua:447
 ShowMacroText = <function> defined @Dominos/Dominos.lua:606
 GetDatabaseDefaults = <function> defined @Dominos/Dominos.lua:242
 SaveProfile = <function> defined @Dominos/Dominos.lua:300
 ToggleFrames = <function> defined @Dominos/Dominos.lua:554
 OnProfileChanged = <function> defined @Dominos/Dominos.lua:120
 GetName = <function> defined @AddOnSkins/Libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 RegisterCallback = <function> defined @AddOnSkins/Libs/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 name = "Dominos"
 HideFrames = <function> defined @Dominos/Dominos.lua:548
 Disable = <function> defined @AddOnSkins/Libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
 LIBKEYBOUND_DISABLED = <function> defined @Dominos/Dominos.lua:107
 BlizzardActionButtons = <table> {
 }
 Print = <function> defined @AddOnSkins/Libs/Ace3/AceConsole-3.0/AceConsole-3.0.lua:50
 OnLaunch = <function> defined @
