### ISSUE TITLE
Weird action bar paging behavior when modifiers include CTRL-button

### ISSUE THREAD

**Issue by melforx** [tullamods/Dominos#834]
Hidden empty action buttons flash for a short time on paging when modifiers include CTRL-button, delaying the paging process when switching between different bars fast. 

**Addon Version**
Problem first occured in 10.2.12

**World of Warcraft Version**
Retail

I currently use 10.2.11 as a workaround.

**Comment by melforx** [comment]
Resolved with v10.2.19, Thanks a lot!

**Comment by melforx** [comment]
Reoccuring since v10.2.20 again

**Comment by Tuller** [comment]
I actually never implemented anything to address this, so it makes sense that it is still an issue

**Comment by AbelardTullus** [comment]
I'm encountering this issue as well, there's a delay to actions appearing and the frames of the actions disappearing when the modifier is released.

Default
![Default](https://github.com/tullamods/Dominos/assets/20971561/3c51efd9-a1de-40dd-bd4a-67a9a74c2ef7)

Held (there are supposed to be 5 buttons here)
![Held1](https://github.com/tullamods/Dominos/assets/20971561/9c78b44e-75ab-427b-aaca-a8a550e0e0ab)

Held (after delay)
![Held2](https://github.com/tullamods/Dominos/assets/20971561/911a936c-a0d1-4895-89b5-ac9b47358572)

Released (the frames of the buttons linger before disappearing)
![Release](https://github.com/tullamods/Dominos/assets/20971561/d31f84ed-9feb-468a-a699-77a1a0f541e0)
