### ISSUE TITLE
Warrior Stance paging not working?

### ISSUE THREAD

**Issue by MiceyRylus** [tullamods/Dominos#923]
Tried to reset completly deleting .lua and reinstalling addons and still no paging

**Comment by MiceyRylus** [comment]
I guess that might not be a feature anymore since theres no stance dancing?

**Comment by Tuller** [comment]
11.1.6 should resolve this

**Comment by Road-block** [comment]
Should that last push fix class bar not showing too?

I still don't get a classbar on the Monk for its stances.

**Comment by Road-block** [comment]
LibDualSpec 1.26.0 errors (one of Dominos embeds) errors on MoP prepatch btw.
I know it's not a Dominos problem per se but not sure how quick the turnaround for fixes would be (I'll open a ticket with them)

It does an API check on existence of `GetTalentTabInfo` to run code for "old" talents vs new and it has unintended results as Blizzard has kept that in Deprecated API so it exists in _G at the moment.

An easy fix would be to reverse the logic from 
```lua
if GetTalentTabInfo then -- Pre-5.0
  -- 
elseif C_SpecializationInfo.GetSpecialization then -- 5.0 - 9.x
```
in current LibDualSpec to
```lua
if C_SpecializationInfo.GetSpecialization then -- 5.0 - 9.x
  --
elseif GetTalentTabInfo then -- Pre-5.0
```

**Comment by Road-block** [comment]
https://github.com/AdiAddons/LibDualSpec-1.0/issues/6

**Comment by Cabro** [comment]
Confirmed, monk stance bar still missing.

**Comment by Tuller** [comment]
Monk stance issues should be resolved now.
